# Generated by Django 4.2.4 on 2023-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='GOST:)', max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True)),
                ('phoneNumber', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Player',
            },
        ),
    ]
